### PR TITLE
Add my sentence

### PR DESCRIPTION
**Pull request by Bbabiker**
I added a sentence to your story !

### CODE REVIEW

**Comment by dmyoung9** [comment]
Isn't it supposed to be at the end? 🤔

**Comment by Bbabiker** [comment]
I did add it as last sentence

**Comment by Bbabiker** [comment]
Oh, I see what you saying, so it should be at the end of your sentence lol. I'll fix it.

**Comment by sjbaraho** [comment]
Sentence is not at the end of the story.

**Pull request closed without merging**
